### ISSUE TITLE
shr3d should not limit point cloud formats to LAS and BPF

### ISSUE THREAD

**Issue by chambbj** [pubgeo/pubgeo#5]
In doing this, you forfeit the opportunity for PDAL to read any format but LAS or BPF (including LAZ!).

https://github.com/pubgeo/pubgeo/blob/f38f4bfb1fa7ffd6651d1fbf899ab55f958d4bc3/src/shr3d/main.cpp#L91

If changed to a simple `else`, you can lean on PDAL to attempt to infer the reader for you. If one cannot be found, PDAL throws an error and the output of shr3d looks something like.

```
Reading DSM as SHORT.
File Type = .foo
Cannot determine reader for input file: whatever.foo
```

**Comment by slipperysaxophone** [comment]
Is this issue still relevant, or was it already dealt with, but unclosed?
@fosterkh

**Comment by fosterkh** [comment]
It's still relevant

**Comment by chambbj** [comment]
Still there -- https://github.com/pubgeo/pubgeo/blob/master/src/shr3d/main.cpp#L98. To be clear, my suggestion is to not check the extension at all, just pass it to PDAL and let it figure out whether or not it can open the file. A very simply change as long as you are okay with having PDAL emit the error vice shr3d.
